config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/challenges/try', to: 'pages#try_challenge'

  get '/courses/physics', to: 'pages#course_physics'
  get '/courses', to: 'pages#courses'

  get '/courses/viewer/', to: 'pages#viewer'
  get '/courses/viewer/challenges', to: 'pages#viewer'

  resources :users, except: [:new, :destroy]
  get '/register', to: 'users#new'
  
  resources :games do
    member do
      post 'like'
    end
  end

  resources :articles do
    resources :comments
  end
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :tags, only: [:new, :create, :show]

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :game_tags, dependent: :destroy
  has_many :tags, through: :game_tags
  
  validates :user_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :summary, presence: true, length: {minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 500}

  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  default_scope -> { order(updated_at: :desc) }

  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like:false).size
  end

  private
  
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  before_action :set_game, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @games = Game.paginate(page: params[:page], per_page: 4)
  end
  
  def show

  end
  
  def new
    @game = Game.new
  end
  
  def create
    @game = Game.new(game_params)
    @game.user = current_user
    
    if @game.save
      flash[:success] = "Your game was created successfully!"
      redirect_to games_path
    else
      render :new
    end
  end
  
  def edit

  end
  
  def update
    if @game.update(game_params)
      flash[:success] = "Your game was updated successfully!"
      redirect_to game_path(@game)
    else
      render :edit
    end
  end
  
  def destroy
    @game = Game.find(params[:id]).destroy
    flash[:success] = "Game Deleted"
    redirect_to games_path
  end
  
  def like
    like = Like.create(like: params[:like], user: current_user, game: @game)
    
    if like.valid?
      flash[:success] = "Your selection was succesful"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a game once"
      redirect_to :back
    end
  end
  
  private
    
    def game_params
      params.require(:game).permit(:name,:summary,:description,:picture,tag_ids: [])
    end
    
    def require_same_user
      if current_user != @game.user and !current_user.admin?
        flash[:danger] = "You can only edit your own games"
        redirect_to games_path
      end
    end
    
    def set_game
      @game = Game.find(params[:id])
    end
    
    def admin_user
      redirect_to games_path unless current_user.admin?  
    end
  
end

app/views/games/_form.html.erb
<%= render 'shared/errors', obj: @game %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@game, html: {multipart: true}) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      
      <strong>Tags:</strong>
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
      <br><br>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
      </span>
      
      <%= f.submit(@game.new_record? ? 'Create Game' : 'Edit Game', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#game_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if( size_in_megabytes > 5 ){
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/games/edit.html.erb
<%= render 'shared/page_title', title: "Edit Game" %>

<%= render 'form' %>

app/views/games/index.html.erb
<%= render 'shared/page_title', title: "All Games" %>

<ul class="nav nav-tabs">
  <li class='active'><%= link_to "Games", games_path %></li>
  <li><%= link_to "Users", users_path %></li>
</ul>

<%= will_paginate %>

<% @games.each do |game| %>
  <div class="row">
    
    <div class="col-md-2">
      <section class="user_info center">
        <%= link_to gravatar_for( game.user, size: 100 ), user_path(game.user) %>
        <h5><b>Author: <%= game.user.username %></b></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      <h4><%= link_to game.name, game_path(game) %></h4>
      <p><%= game.summary %></p>
      <% if game.tags.any? %>
        <p>Tags: <%= render game.tags %></p>
      <% end %>
      <p>
        <span class='quiet'><small>created: <%= time_ago_in_words(game.created_at) %>, </small></span>
        <span class='quiet'><small>updated: <%= time_ago_in_words(game.updated_at) %></small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_game_path(game, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= game.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_game_path(game, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= game.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    
    <div class="col-md-4">
      <%= image_tag(game.picture.url, size:"250x150", class: "gravatar") if game.picture? %>
    </div>
    
  </div>
  <hr/>
<% end %>

<%= will_paginate %>

app/views/games/new.html.erb
<%= render 'shared/page_title', title: "Create a new Game" %>

<%= render 'form' %>

app/views/games/show.html.erb
<%= render 'shared/page_title', title: @game.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@game.user, size: 200), user_path(@game.user)%>
    <p>
      <h5>Brought to you by: <%= @game.user.username %></h5>
    </p>
  </div>
  
  <div class="col-md-8">
    <% if logged_in? and (@game.user == current_user || current_user.admin?) %>
      <%= link_to "Edit this Game", edit_game_path(@game), class: "btn btn-success pull-right" %>
    <% end %>
    <% if logged_in? and current_user.admin? %>
      <%= link_to "[Delete Game]", @game, method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
    <h3><%= @game.summary %></h3>
    <div class="show_game">
      <%= image_tag(@game.picture.url, class: "gravatar") if @game.picture? %>
    </div>
    <div class="well">
      <% if @game.tags.any? %>
        <p>Tags: <%= render @game.tags %></p>
      <% end %>
      <p><strong>Steps:</strong></p>
      <%= simple_format(@game.description) %>
      <div class="pull-right">
        <%= link_to like_game_path(@game, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @game.thumbs_up_total %>
        <% end %>
        &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_game_path(@game, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @game.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to "Return to Games Listing", games_path, class: "btn btn-warning btn-small" %></h5>