config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/challenges/try', to: 'pages#try_challenge'

  get '/courses/physics', to: 'pages#course_physics'
  get '/courses', to: 'pages#courses'

  get '/courses/viewer/', to: 'pages#viewer'
  get '/courses/viewer/challenges', to: 'pages#viewer'

  resources :users, except: [:new, :destroy]
  get '/register', to: 'users#new'
  
  resources :games do
    member do
      post 'like'
    end
  end

  resources :articles do
    resources :comments
  end
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :tags, only: [:new, :create, :show]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :game_tags
  has_many :games, through: :game_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  before_action :require_user, except: [:show]
  
  def new
    @tag = Tag.new
  end
  
  def create
    @tag = Tag.new(tag_params)
    
    if @tag.save
      flash[:success] = "Tag was created successfully"
      redirect_to games_path
    else
      render 'new'
    end
  end
  
  def show
    @tag = Tag.find(params[:id])
    @games = @tag.games.paginate(page: params[:page], per_page: 4)
  end
  
  private
  
    def tag_params
      params.require(:tag).permit(:name)
    end
  
end

app/views/tags/_tag.erb
<span class='quiet'><%= link_to tag.name, tag_path(tag) %> </span>

app/views/tags/new.html.erb
<%= render 'shared/page_title', title: "Create a new Tag" %>

<%= render 'shared/errors', obj: @tag %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @tag do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.submit 'Create Tag', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<%= render 'shared/page_title', title: "Games for : " + @tag.name + " tag" %>

<ul class="nav nav-tabs">
  <li class='active'><%= link_to "Games", games_path %></li>
  <li><%= link_to "Users", users_path %></li>
</ul>

<%= will_paginate @games %>

<% @tag.games.each do |game| %>
  <div class="row">
    
    <div class="col-md-2">
      <section class="user_info center">
        <%= link_to gravatar_for( game.user, size: 100 ), user_path(game.user) %>
        <h5><b>Author: <%= game.user.username %></b></h5>
      </section>
    </div>
    
    <div class="col-lg-6 well">
      <h4><%= link_to game.name, game_path(game) %></h4>
      <p><%= game.summary %></p>
      <p>Tags: <%= render game.tags %></p>
      <p>
        <span class='quiet'><small>created: <%= time_ago_in_words(game.created_at) %>, </small></span>
        <span class='quiet'><small>updated: <%= time_ago_in_words(game.updated_at) %></small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_game_path(game, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= game.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_game_path(game, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= game.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    
    <div class="col-md-4">
      <%= image_tag(game.picture.url, size:"250x150", class: "gravatar") if game.picture? %>
    </div>
    
  </div>
  <hr/>
<% end %>

<%= will_paginate @games %>