config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/challenges/try', to: 'pages#try_challenge'

  get '/courses/physics', to: 'pages#course_physics'
  get '/courses', to: 'pages#courses'

  get '/courses/viewer/', to: 'pages#viewer'
  get '/courses/viewer/challenges', to: 'pages#viewer'

  resources :users, except: [:new, :destroy]
  get '/register', to: 'users#new'
  
  resources :games do
    member do
      post 'like'
    end
  end

  resources :articles do
    resources :comments
  end
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :tags, only: [:new, :create, :show]

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Gamify School 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
  <header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Gamify", root_path, class: "btn btn-lg btn-success", id: "logo" %>
      <div class="nav_item"> <%= link_to "Blog", articles_path, class: "btn btn-default btn-warning" %> </div>
      <div class="nav_item"> <%= link_to "Games", games_path, class: "btn btn-default btn-warning" %> </div>
      <div class="nav_item"> <%= link_to "Courses", courses_path, class: "btn btn-default btn-warning" %> </div>
      <ul class="nav_ul_item">
        <li class="dropdown">
            <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
              Tags <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <% Tag.all.each do |tag| %>
                <li><%= link_to tag.name, tag_path(tag) %></li>
              <% end %>
              <% if logged_in? %>
                <li class="divider"></li>
                <li>
                  <%= link_to(new_tag_path) do %>
                  New Tag
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
      </ul>
      <% if logged_in? %>  
        <div class="nav_item"> <%= link_to "New Game", new_game_path, class: "btn btn-default btn-warning" %> </div>
        <ul class="nav_item">
          <li class="dropdown">
            <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
              <%= current_user.username %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <div class="nav_item">
            <%= link_to "Log in", login_path, class: "btn btn-success" %>
              <%= link_to "Sign up now!", register_path, class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <base href="/courses/viewer/" />
  <title>Gamify School</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900' rel='stylesheet' type='text/css'>-->
  <!--<scrip type="text/javascript" src="http://webplayer.unity3d.com/download_webplayer-3.x/3.0/uo/UnityObject2.js"></scrip>-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">
  <%= render 'layouts/messages' %>

  <%= yield %>

  <%= render '/layouts/footer' %>
</div>

</body>

</html>

app/views/layouts/exhibition.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Gamify School - Learn by playing</title>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag 'exhibition', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'exhibition', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>

</html>

app/views/layouts/high_beauty.html.erb
<!DOCTYPE html>
<html>
<head>
  <base href="/courses/viewer/" />
  <title>Gamify School</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">
  <%= render 'layouts/messages' %>

  <%= yield %>

  <%= render '/layouts/footer' %>
</div>

</body>

</html>